分解矩阵 $A = LU$ (把一个矩阵分解成一个下三角矩阵乘上一个上三角矩阵的形式)

$$
\left(\begin{array}{llll}
a_{11} & a_{12} & ...& a_{1n}\\
a_{21} & a_{22} & ...& a_{2n} \\
... & ... & ... & ...\\
a_{n1}& a_{n2}& ...& a_{nn}
\end{array}\right) =
\left(\begin{array}{llll}
1 &  & & \\
l_{21} & 1 & &  \\
... & ... & ... & ...\\
l_{n1}& l_{n2}& ...& 1
\end{array}\right)
\left(\begin{array}{llll}
u_{11} & u_{12} & ...& u_{1n}\\
 & u_{22} & ...& u_{2n} \\
... & ... & ... & ...\\
& & & u_{nn}
\end{array}\right)
$$

推导：

第一行：

$$
[a_{11}, a_{12} ... a_{1n}] = [u_{11}, u_{12} ... u_{1n}]
$$

第－列．$\quad \begin{aligned} & l_{21} u_{11}=a_{21} \\ & l_{31} u_{11}=a_{31} \\ & ...\end{aligned} \rightarrow \quad\left[\begin{array}{c}l_{21} \\ l_{31} \\ \vdots \\ l_{n 1}\end{array}\right]=\left[\begin{array}{c}a_{21} \\ a_{31} \\ \vdots \\ a_{n 1}\end{array}\right] \times \frac{1}{a_{11}}$

第二行

$$
\begin{aligned}
& l_{21} u_{12}+u_{22}=a_{22} \\
& l_{21} u_{13}+u_{23}=a_{23}  \\
& ... \\
& a_{2 k}=l_{21} u_{1 k}+u_{2 k}=l_{21} a_{1 k}+u_{2 k}\\
& \rightarrow u_{2 k}=a_{2 k}-l_{21} a_{1 k} \quad(k=2,3, \cdots, n)
\end{aligned}
$$


第二列

$$
\begin{aligned}
& l_{31} u_{12}+l_{32} u_{22}=a_{32} \\
& l_{41} u_{12}+l_{42} u_{22}=a_{42} \\
& ...\\
& \rightarrow l_{m 1} u_{12}+l_{m 2} u_{22}=a_{m 2} \quad(m=3,4, \cdots, n) .
\end{aligned}
$$

（3）第三行

$$
u_{3 k}=a_{3 k}-l_{31} u_{1 k}-l_{32} u_{2 k} \quad(k=3,4, \cdots, n)
$$


第三列

$$
l_{m 1} u_{13}+l_{m 2} u_{23}+l_{m 3} u_{33}=a_{m 3} \quad(m=4,5, \cdots, n)
$$

（4）第 $r$ 行。

$$
\begin{aligned}
u_{r k} & =a_{r k}-l_{r 1} u_{1 k}-l_{r 2} u_{2 k} \cdots-l_{r, r-1} u_{r-1, k} \\
& =a_{r k}-\left[l_{r 1}, l_{r 2}, ... l_{r, r-1}\right]\left[\begin{array}{c}
u_{1 k} \\
u_{2 k} \\
\vdots \\
u_{r-1, k}
\end{array}\right] \quad(k=r, r+1, \cdots n)
\end{aligned}
$$


第 $r$ 列。

$$
\begin{aligned}
& l_{m 1} u_{1 r}+l_{m 2} u_{2 r}+\cdots+l_{m r} u_{r r}=a_{m r} \\
& l_{m r}=\frac{a_{m r}-\left[l_{m_1,} l_{m_2} \cdots l_{m, r-1}\right]\left[\begin{array}{c}
u_{1 r} \\
u_{r r} \\
\vdots \\
u_{r-1, r}
\end{array}\right]}{u_{r r}}(m=r+1, r+2, \cdots n)
\end{aligned}
$$


举例：设有矩阵

$$
A=\left(\begin{array}{ccc}
1 & 2 & -1 \\
2 & 1 & -2 \\
-3 & 1 & 1
\end{array}\right) 
$$

则分解后有形式
$$
L=\left(\begin{array}{ccc}
1 &  &  \\
l_{21} & 1 & \\
l_{31} & l_{32} & 1
\end{array}\right) \quad 
U=\left(\begin{array}{ccc}
u_{11} & u_{12} & u_{13} \\
 & u_{22} & u_{23} \\
 & & u_{33}
\end{array}\right)
$$
由前面的推导，可得
$$
\begin{aligned}
& u_{11}=1,  u_{12} = 2, u_{13} = -1\\
& l_{21}=\frac{a_{21}}{a_{11}}=2,  l_{31}=\frac{a_{31}}{a_{11}}=-3\\
& u_{22}=a_{22}-l_{21} a_{12}=-3 \\
& u_{23}=a_{23}-l_{21} a_{13}=0 \\
& l_{32}=\frac{a_{32}-l_{31}u_{12}}{u_{22}}=-\frac{7}{3} \\
& u_{33}=a_{33}-\left[l_{31} \quad l_{32}\right]\left[\begin{array}{c}
u_{13} \\
u_{23}
\end{array}\right] =-2
\end{aligned}
$$

综上

$$
L=\left(\begin{array}{ccc}
1 &  &  \\
2 & 1 & \\
-3 & -\frac{7}{3} & 1
\end{array}\right) \quad 
U=\left(\begin{array}{ccc}
1 & 2 & -1 \\
 & -3 & 0 \\
 & & -2
\end{array}\right)
$$

写代码，首先写出上下三角回代解线性方程组的算法，

In [2]:
import numpy as np

def reg_utm(A, b):
    """
    解上三角方程组 回代算法
    A : 系数矩阵 必须为上三角
    b : 右端常数
    X : 求得的解向量
    使用要求：A的对角线处元素不为0
    """
    # 检查对角线元素是否为零
    if np.any(np.diag(A) == 0):
        raise ValueError("Error: 对角线上有0元素，不能使用该函数")

    n = len(b)
    X = np.zeros(n)
    X[n - 1] = b[n - 1] / A[n - 1, n - 1]

    for k in range(n - 2, -1, -1):
        t = np.dot(A[k, k + 1:n], X[k + 1:n])
        X[k] = (b[k] - t) / A[k, k]

    return X



# 定义一个具体的上三角矩阵 A 和常数向量 b
A = np.array([[2, 3, 0],
              [0, 1, 4],
              [0, 0, 5]], dtype=float)

b = np.array([5, 6, 15], dtype=float)

# 使用 reg_utm 函数求解
X = reg_utm(A, b)

# 输出结果
print("解向量 X:", X)

# 验证结果
# 计算 A @ X
result = np.dot(A, X)

print("验证：A @ X =", result)
print("应等于 b:", b)

解向量 X: [11.5 -6.   3. ]
验证：A @ X = [ 5.  6. 15.]
应等于 b: [ 5.  6. 15.]


In [3]:
def push_ltm(A, b):
    """
    解下三角方程组 前推算法
    A : 系数矩阵，必须为下三角
    b : 右端常数
    X : 求得的解向量
    使用要求：对角线处元素不为0
    """
    # 检查对角线元素是否为零
    if np.any(np.diag(A) == 0):
        raise ValueError("Error: 对角线上有0元素，不能使用该函数")

    n = len(b)
    X = np.zeros(n)
    X[0] = b[0] / A[0, 0]

    for k in range(1, n):
        t = np.dot(A[k, :k], X[:k])
        X[k] = (b[k] - t) / A[k, k]

    return X



# 测试具体矩阵
A = np.array([[2, 0, 0],
              [3, 1, 0],
              [1, 4, 5]], dtype=float)

b = np.array([4, 7, 30], dtype=float)

# 使用 push_ltm 函数求解
X = push_ltm(A, b)

# 输出结果
print("解向量 X:", X)

# 验证结果
# 计算 A @ X
result = np.dot(A, X)

print("验证：A @ X =", result)
print("应等于 b:", b)

解向量 X: [2.  1.  4.8]
验证：A @ X = [ 4.  7. 30.]
应等于 b: [ 4.  7. 30.]


In [4]:
def back_substitution_two(L, U, b):
    """
    Ly = b, Ux = y
    b : 列向量
    返回: 解向量 X
    """
    y = push_ltm(L, b)
    X = reg_utm(U, y)
    return X

In [5]:
def LU_factorization(A):
    """
    LU 分解
    A : 系数矩阵
    返回 L 和 U，使得 A = LU

    """
    n = len(A)
    A = A.astype(float)  # 确保进行浮点计算

    # 更新 A 的第 1 列
    A[1:n, 0] = A[1:n, 0] * (1 / A[0, 0])

    # 主循环
    for r in range(1, n):
        # 更新 A 的第 r 行
        for k in range(r, n):
            A[r, k] = A[r, k] - np.dot(A[r, 0:r], A[0:r, k])

        # 更新 A 的第 r 列
        for m in range(r + 1, n):
            A[m, r] = (A[m, r] - np.dot(A[m, 0:r], A[0:r, r])) * (1 / A[r, r])

    # 提取 L 和 U
    L = np.tril(A, -1) + np.eye(n)
    U = np.triu(A, 0)

    return L, U


In [7]:
# 测试具体矩阵
A = np.array([[1, 2, -1],
              [2, 1, -2],
              [-3, 1, 1]], dtype=float)

b1 = np.array([3, 3, -6], dtype=float)

# LU分解
L, U = LU_factorization(A)

# 输出L和U
print("L:\n", L)
print("U:\n", U)

# 测试多个b向量
b = np.array([[3, 3, -6],
              [1, 2, 5],
              [4, 9, 8],
              [10, 2, 5]], dtype=float)

m = len(b)
X = []

for i in range(m):
    solution = back_substitution_two(L, U, b[i])
    X.append(solution)
    
# 输出解
for i in range(m):
    print(f"解向量 X[{i}]:", X[i])

L:
 [[ 1.          0.          0.        ]
 [ 2.          1.          0.        ]
 [-3.         -2.33333333  1.        ]]
U:
 [[ 1.  2. -1.]
 [ 0. -3.  0.]
 [ 0.  0. -2.]]
解向量 X[0]: [3. 1. 2.]
解向量 X[1]: [-3. -0. -4.]
解向量 X[2]: [ -6.5         -0.33333333 -11.16666667]
解向量 X[3]: [1.5 6.  3.5]


PLU分解
主要是 通过 P 来达到一个 列主元消去法的效果,
在计算每一层之前,先把列中最大的那个元素换到相对的第一行

In [8]:
def PLU_factorization(A):
    """
    PA = LU分解
    输入: A
    输出: L, U, P
    """
    n = len(A)
    P = np.eye(n)  # 初始置为单位矩阵

    # 第一次行交换
    s = np.argmax(np.abs(A[0:n, 0]))  # 第一列最大元素的位置
    P[[0, s]] = P[[s, 0]]  # 交换行
    A = P @ A  # 用初等矩阵左乘 A

    A[1:n, 0] = A[1:n, 0] * (1 / A[0, 0])  # 求第一层

    for r in range(1, n):
        # 行交换
        p = np.eye(n)  # 用 p 记录每一次的初等矩阵
        s = np.argmax(np.abs(A[r:n, r])) + r  # 找到当前列的最大元素位置
        p[[r, s]] = p[[s, r]]  # 交换行
        A = p @ A  # A的改变
        P = p @ P  # 记录P的变化

        # 求第 r 层
        for k in range(r, n):
            A[r, k] = A[r, k] - np.dot(A[r, :r], A[:r, k])
        for m in range(r + 1, n):
            A[m, r] = (A[m, r] - np.dot(A[m, :r], A[:r, r])) * (1 / A[r, r])

    L = np.tril(A, -1) + np.eye(n)  # 下三角矩阵加上单位矩阵
    U = np.triu(A)  # 上三角矩阵

    return L, U, P

In [11]:
# 测试具体矩阵
A = np.array([[1, 2, -1],
              [2, 1, -2],
              [-3, 1, 1]], dtype=float)

b1 = np.array([3, 3, -6], dtype=float)

# LU分解
L, U, P = PLU_factorization(A)

# 输出 L, U, P
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

print("L*U:\n", L @ U)
print("P*A:\n", P @ A)

# 使用 back_substitution_two 计算解
X1 = back_substitution_two(L, U, P @ b1)

# 输出解
print("解向量 X1:", X1)

P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L:
 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-0.66666667  0.71428571  1.        ]]
U:
 [[-3.          1.          1.        ]
 [ 0.          2.33333333 -0.66666667]
 [ 0.          0.         -0.85714286]]
L*U:
 [[-3.  1.  1.]
 [ 1.  2. -1.]
 [ 2.  1. -2.]]
P*A:
 [[-3.  1.  1.]
 [ 1.  2. -1.]
 [ 2.  1. -2.]]
解向量 X1: [3. 1. 2.]


我们发现它和 python 官方的 PLU 分解的包给出的结果一致 (貌似官方包给出的 P 矩阵多了一次行交换？),

In [17]:
from scipy.linalg import lu

P, L, U = lu(A)

# 输出 L, U, P
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

print("L*U:\n", L @ U)
print("P*A:\n", P @ A)

P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-0.66666667  0.71428571  1.        ]]
U:
 [[-3.          1.          1.        ]
 [ 0.          2.33333333 -0.66666667]
 [ 0.          0.         -0.85714286]]
L*U:
 [[-3.  1.  1.]
 [ 1.  2. -1.]
 [ 2.  1. -2.]]
P*A:
 [[ 2.  1. -2.]
 [-3.  1.  1.]
 [ 1.  2. -1.]]
